package strata

import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.yield

/** Lifecycle states for a chunk being processed. */
enum class ChunkState {
    /** Not yet requested. */
    IDLE,
    /** Queued for generation, waiting for a worker. */
    PENDING,
    /** Actively being generated by a worker coroutine. */
    GENERATING,
    /** Generation complete, waiting for meshing. */
    GENERATED,
    /** Actively being meshed by a worker coroutine. */
    MESHING,
    /** Fully processed and ready for upload. */
    READY,
    /** No longer needed (player moved away), cancellation requested. */
    CANCELLED
}

/** Tracks a chunk's journey through the generation pipeline. */
data class ChunkInfo(
    val key: Long,
    var state: ChunkState = ChunkState.IDLE,
    /** Priority: lower = generate first (distance² from player). */
    var priority: Int = Int.MAX_VALUE,
    /** Monotonically increasing version to detect stale results. */
    var version: Int = 0,
    /** The finished mesh, set when state reaches READY. */
    var mesh: ChunkMesh? = null,
    /** Current LOD level for this chunk. */
    var lodLevel: Int = 0
)

/** A chunk whose blocks need meshing, with cross-chunk border data for culling. */
class MeshRequest(
    val key: Long,
    val version: Int,
    val size: Int,
    val blocks: UShortArray,
    val east: UShortArray?,
    val west: UShortArray?,
    val north: UShortArray?,
    val south: UShortArray?,
    val top: UShortArray?,
    val bottom: UShortArray?,
    /** LOD level for this mesh request. */
    val lodLevel: Int = 0
)

class MeshResult(val key: Long, val version: Int, val mesh: ChunkMesh)

/**
 * Streams an infinite cubic world around the player without ever blocking the
 * render thread, using structured coroutines with:
 *
 *  - **Priority-based loading**: closer chunks generate first (BFS from player).
 *  - **Cancellation**: chunks that leave render distance are cancelled, freeing
 *    worker slots for closer chunks.
 *  - **State tracking**: each chunk has a lifecycle state for diagnostics and UI.
 *  - **Configurable parallelism**: worker count scales with CPU cores.
 *  - **Thread safety**: only the main thread modifies shared state.
 *  - **LOD system**: distant chunks use simplified meshes for iGPU performance.
 *  - **Incremental updates**: only changed chunks are rebuilt in the GPU buffer.
 *
 * Uses 3D chunk addressing (cx, cy, cz) so vertical slices load/unload
 * independently — critical for caves, deep underground, and sky features.
 */
class WorldStreamer(
    val world: World,
    val renderDistance: Int = 4,
    val verticalRenderDistance: Int = 3,
    scope: CoroutineScope,
    /** Number of worldgen workers. Defaults to `availableProcessors().coerceIn(2, 8)`. */
    val genWorkerCount: Int = availableProcessors().coerceIn(2, 8),
    /** Number of meshing workers. Defaults to `availableProcessors().coerceIn(2, 12)`. */
    val meshWorkerCount: Int = availableProcessors().coerceIn(2, 12)
) {
    private val genChannel = Channel<Long>(Channel.UNLIMITED)
    private val genResults = Channel<GenResult>(Channel.UNLIMITED)
    private val meshChannel = Channel<MeshRequest>(Channel.UNLIMITED)
    private val meshResults = Channel<MeshResult>(Channel.UNLIMITED)

    private val meshes = HashMap<Long, ChunkMesh>()
    private val requested = HashSet<Long>()
    private val versions = HashMap<Long, Int>()

    /** Per-chunk lifecycle tracking. Only modified by main thread. */
    private val chunkStates = HashMap<Long, ChunkInfo>()

    /**
     * Thread-safe set of cancelled chunk keys. Workers check this to skip
     * cancelled chunks. Only the main thread adds/removes keys.
     */
    private val cancelledKeys = HashSet<Long>()

    /** Set of chunk keys that have new meshes since last upload. */
    private val dirtyChunks = HashSet<Long>()

    /** Observable count of chunks in each state (for HUD). */
    private val _stateCounts = MutableStateFlow(ChunkStateCounts())
    val stateCounts: StateFlow<ChunkStateCounts> = _stateCounts.asStateFlow()

    /** Set when the mesh set changed; caller rebuilds + uploads the buffer. */
    var dirty = false
        private set

    /**
     * Monotonic counter bumped on every mesh-set change. The render loop
     * captures it when it starts a background rebuild and, on completion,
     * only keeps the mesh dirty if the epoch moved (i.e. genuinely new
     * meshes arrived during the build).
     */
    private var epoch = 0

    /** Shared flow for chunk-ready events (for future UI integration). */
    private val _chunkReady = MutableSharedFlow<Long>(extraBufferCapacity = 64)

    fun meshEpoch(): Int = epoch

    /** Get the set of chunks that have new meshes since last upload. */
    fun getDirtyChunks(): Set<Long> = dirtyChunks.toSet()

    /** Clear the dirty chunks set after incremental update. */
    fun clearDirtyChunks() {
        dirtyChunks.clear()
        dirty = false
    }

    private val workerJobs = ArrayList<Job>()

    init {
        // Multiple independent worldgen workers: generateChunk is a pure,
        // seed-deterministic function (no shared state touched).
        // Workers check the cancelledKeys set (read-only) to skip cancelled chunks.
        repeat(genWorkerCount) { _ ->
            workerJobs += scope.launch(Dispatchers.Default) {
                for (key in genChannel) {
                    // Check cancellation (read-only check on thread-safe set)
                    if (key in cancelledKeys) continue

                    try {
                        val cx = world.chunkX(key)
                        val cy = world.chunkY(key)
                        val cz = world.chunkZ(key)

                        // Yield periodically to allow cancellation checks
                        yield()

                        val chunk = world.generateChunk(cx, cy, cz)

                        // Check cancellation after generation (CPU-intensive)
                        if (key in cancelledKeys) continue

                        // Send result back — main thread updates state
                        genResults.send(GenResult(key, chunk))
                    } catch (_: CancellationException) {
                        // Worker cancelled by scope.cancel() — exit gracefully
                    }
                }
            }
        }

        // Multiple meshing workers: each request carries its own immutable
        // snapshot + border data.
        repeat(meshWorkerCount) { _ ->
            workerJobs += scope.launch(Dispatchers.Default) {
                for (req in meshChannel) {
                    // Check cancellation (read-only check on thread-safe set)
                    if (req.key in cancelledKeys) continue

                    try {
                        // Yield to allow cancellation
                        yield()

                        val mesh = ChunkMesher.generateMesh(req.size, req.blocks, req.lodLevel) { nx, ny, nz ->
                            borderLookup(req, nx, ny, nz)
                        }

                        // Check cancellation after meshing
                        if (req.key in cancelledKeys) continue

                        // Send result back — main thread updates state
                        meshResults.send(MeshResult(req.key, req.version, mesh))
                    } catch (_: CancellationException) {
                        // Worker cancelled by scope.cancel() — exit gracefully
                    }
                }
            }
        }
    }

    fun meshFor(key: Long): ChunkMesh? = meshes[key]
    fun meshKeys(): Set<Long> = meshes.keys

    /** Get the state of a specific chunk (for HUD diagnostics). */
    fun getChunkState(key: Long): ChunkState = chunkStates[key]?.state ?: ChunkState.IDLE

    /** Get the LOD level of a specific chunk. */
    fun getChunkLod(key: Long): Int = chunkStates[key]?.lodLevel ?: 0

    /** Call after the caller has rebuilt + uploaded its GPU buffer. */
    fun markMeshUploaded() {
        dirty = false
        dirtyChunks.clear()
    }

    /**
     * Compute LOD level based on distance from player.
     * Returns 0 (full detail) for close chunks, increasing for distant chunks.
     */
    private fun computeLod(playerCx: Int, playerCy: Int, playerCz: Int, chunkCx: Int, chunkCy: Int, chunkCz: Int): Int {
        val dx = chunkCx - playerCx
        val dy = chunkCy - playerCy
        val dz = chunkCz - playerCz
        val distSq = dx * dx + dy * dy + dz * dz
        return when {
            distSq <= 4 -> 0   // Within 2 chunks: full detail
            distSq <= 25 -> 1  // Within 5 chunks: half detail
            distSq <= 100 -> 2 // Within 10 chunks: quarter detail
            else -> 3          // Far away: eighth detail
        }
    }

    /** Called every frame from the main thread with the player's chunk coords. */
    fun update(playerCx: Int, playerCy: Int, playerCz: Int) {
        // 1. Place generated chunks, then ask for their meshes (and neighbors').
        while (true) {
            val res = genResults.tryReceive()
            if (res.isClosed || res.isFailure) break
            val gen = res.getOrThrow()
            requested.remove(gen.key)

            // Update state on main thread only
            val info = chunkStates[gen.key]
            if (info != null && info.state != ChunkState.CANCELLED) {
                info.state = ChunkState.GENERATED
            }

            val cx = world.chunkX(gen.key)
            val cy = world.chunkY(gen.key)
            val cz = world.chunkZ(gen.key)
            world.putChunk(cx, cy, cz, gen.chunk)
            requestMesh(gen.key, playerCx, playerCy, playerCz)
            // Horizontal neighbors
            requestMesh(world.chunkKey(cx - 1, cy, cz), playerCx, playerCy, playerCz)
            requestMesh(world.chunkKey(cx + 1, cy, cz), playerCx, playerCy, playerCz)
            requestMesh(world.chunkKey(cx, cy, cz - 1), playerCx, playerCy, playerCz)
            requestMesh(world.chunkKey(cx, cy, cz + 1), playerCx, playerCy, playerCz)
            // Vertical neighbors
            requestMesh(world.chunkKey(cx, cy + 1, cz), playerCx, playerCy, playerCz)
            requestMesh(world.chunkKey(cx, cy - 1, cz), playerCx, playerCy, playerCz)
        }

        // 2. Compute desired chunks within render distance (3D) with priority.
        val desired = HashSet<Long>()
        for (dx in -renderDistance..renderDistance) {
            for (dy in -verticalRenderDistance..verticalRenderDistance) {
                for (dz in -renderDistance..renderDistance) {
                    val key = world.chunkKey(playerCx + dx, playerCy + dy, playerCz + dz)
                    desired.add(key)
                }
            }
        }

        // 3. Cancel chunks that left render distance.
        for (key in chunkStates.keys.toList()) {
            if (key !in desired) {
                cancelChunk(key)
            }
        }

        // 4. Request chunks we don't have yet, with priority based on distance.
        for (key in desired) {
            if (key !in requested && !world.hasChunk(key)) {
                val info = chunkStates.getOrPut(key) { ChunkInfo(key) }
                if (info.state == ChunkState.IDLE || info.state == ChunkState.CANCELLED) {
                    // Compute priority: distance² from player (lower = generate first)
                    val cx = world.chunkX(key)
                    val cy = world.chunkY(key)
                    val cz = world.chunkZ(key)
                    val distSq = (cx - playerCx) * (cx - playerCx) +
                                 (cy - playerCy) * (cy - playerCy) +
                                 (cz - playerCz) * (cz - playerCz)
                    info.priority = distSq
                    info.state = ChunkState.PENDING
                    info.version++
                    requested.add(key)
                    genChannel.trySend(key)
                }
            } else if (key in chunkStates && key !in requested) {
                // Update priority and LOD for chunks already being processed
                val info = chunkStates[key]!!
                val cx = world.chunkX(key)
                val cy = world.chunkY(key)
                val cz = world.chunkZ(key)
                val distSq = (cx - playerCx) * (cx - playerCx) +
                             (cy - playerCy) * (cy - playerCy) +
                             (cz - playerCz) * (cz - playerCz)
                info.priority = distSq

                // Check if LOD needs to change
                val newLod = computeLod(playerCx, playerCy, playerCz, cx, cy, cz)
                if (info.lodLevel != newLod && info.state == ChunkState.READY) {
                    // LOD changed — re-mesh with new LOD level
                    info.lodLevel = newLod
                    requestMesh(key, playerCx, playerCy, playerCz)
                }
            }
        }

        // 5. Unload chunks that fell outside render distance.
        for (key in world.loadedKeys.toList()) {
            if (key !in desired) {
                world.removeChunk(key)
                meshes.remove(key)
                versions.remove(key)
                chunkStates.remove(key)
                cancelledKeys.remove(key)
                dirtyChunks.add(key) // Mark as changed (removed)
                dirty = true
                epoch++
            }
        }

        // 6. Store finished meshes.
        while (true) {
            val res = meshResults.tryReceive()
            if (res.isClosed || res.isFailure) break
            val mr = res.getOrThrow()

            // Update state on main thread only
            val info = chunkStates[mr.key]
            if (info != null && info.state != ChunkState.CANCELLED &&
                versions[mr.key] == mr.version && world.hasChunk(mr.key)) {
                meshes[mr.key] = mr.mesh
                info.state = ChunkState.READY
                info.mesh = mr.mesh
                dirtyChunks.add(mr.key) // Mark as changed for incremental update
                dirty = true
                epoch++
            }
        }

        // 7. Update state counts for HUD
        updateStateCounts()
    }

    /** Cancel a chunk that's no longer needed. Only called from main thread. */
    private fun cancelChunk(key: Long) {
        val info = chunkStates[key] ?: return
        if (info.state != ChunkState.READY && info.state != ChunkState.IDLE) {
            info.state = ChunkState.CANCELLED
            cancelledKeys.add(key)
            // Remove from requested set so it can be re-requested if needed
            requested.remove(key)
        }
    }

    /** Re-mesh a chunk and its neighbors after a block edit. */
    fun onBlockEdited(wx: Int, wy: Int, wz: Int, playerCx: Int = 0, playerCy: Int = 0, playerCz: Int = 0) {
        val cx = world.worldToChunkX(wx)
        val cy = world.worldToChunkY(wy)
        val cz = world.worldToChunkZ(wz)
        // Horizontal neighbors
        requestMesh(world.chunkKey(cx, cy, cz), playerCx, playerCy, playerCz)
        requestMesh(world.chunkKey(cx - 1, cy, cz), playerCx, playerCy, playerCz)
        requestMesh(world.chunkKey(cx + 1, cy, cz), playerCx, playerCy, playerCz)
        requestMesh(world.chunkKey(cx, cy, cz - 1), playerCx, playerCy, playerCz)
        requestMesh(world.chunkKey(cx, cy, cz + 1), playerCx, playerCy, playerCz)
        // Vertical neighbors
        requestMesh(world.chunkKey(cx, cy + 1, cz), playerCx, playerCy, playerCz)
        requestMesh(world.chunkKey(cx, cy - 1, cz), playerCx, playerCy, playerCz)
    }

    private fun requestMesh(key: Long, playerCx: Int = 0, playerCy: Int = 0, playerCz: Int = 0) {
        val cx = world.chunkX(key)
        val cy = world.chunkY(key)
        val cz = world.chunkZ(key)
        val chunk = world.getChunk(cx, cy, cz) ?: return

        val info = chunkStates[key]
        if (info != null && info.state == ChunkState.CANCELLED) return

        val version = (versions[key] ?: 0) + 1
        versions[key] = version

        info?.state = ChunkState.MESHING

        // Compute LOD based on distance from player
        val lodLevel = computeLod(playerCx, playerCy, playerCz, cx, cy, cz)
        info?.lodLevel = lodLevel

        meshChannel.trySend(
            MeshRequest(
                key = key,
                version = version,
                size = chunk.size,
                blocks = chunk.snapshot(),
                east = world.borderSlice(cx, cy, cz, BlockFace.EAST),
                west = world.borderSlice(cx, cy, cz, BlockFace.WEST),
                north = world.borderSlice(cx, cy, cz, BlockFace.NORTH),
                south = world.borderSlice(cx, cy, cz, BlockFace.SOUTH),
                top = world.borderSlice(cx, cy, cz, BlockFace.TOP),
                bottom = world.borderSlice(cx, cy, cz, BlockFace.BOTTOM),
                lodLevel = lodLevel
            )
        )
    }

    private fun borderLookup(req: MeshRequest, nx: Int, ny: Int, nz: Int): BlockId {
        // Horizontal borders
        if (nx < 0) return req.west?.let { BlockId(it[ny * req.size + nz]) } ?: BlockId.Air
        if (nx >= req.size) return req.east?.let { BlockId(it[ny * req.size + nz]) } ?: BlockId.Air
        if (nz < 0) return req.south?.let { BlockId(it[nx * req.size + ny]) } ?: BlockId.Air
        if (nz >= req.size) return req.north?.let { BlockId(it[nx * req.size + ny]) } ?: BlockId.Air
        // Vertical borders
        if (ny < 0) return req.bottom?.let { BlockId(it[nx * req.size + nz]) } ?: BlockId.Air
        if (ny >= req.size) return req.top?.let { BlockId(it[nx * req.size + nz]) } ?: BlockId.Air
        return BlockId.Air
    }

    private fun updateStateCounts() {
        var idle = 0; var pending = 0; var generating = 0; var generated = 0
        var meshing = 0; var ready = 0; var cancelled = 0
        for (info in chunkStates.values) {
            when (info.state) {
                ChunkState.IDLE -> idle++
                ChunkState.PENDING -> pending++
                ChunkState.GENERATING -> generating++
                ChunkState.GENERATED -> generated++
                ChunkState.MESHING -> meshing++
                ChunkState.READY -> ready++
                ChunkState.CANCELLED -> cancelled++
            }
        }
        _stateCounts.value = ChunkStateCounts(idle, pending, generating, generated, meshing, ready, cancelled)
    }

    fun cancel() {
        workerJobs.forEach { it.cancel() }
    }
}

/** Aggregate counts of chunks in each lifecycle state. */
data class ChunkStateCounts(
    val idle: Int = 0,
    val pending: Int = 0,
    val generating: Int = 0,
    val generated: Int = 0,
    val meshing: Int = 0,
    val ready: Int = 0,
    val cancelled: Int = 0
) {
    val total: Int get() = idle + pending + generating + generated + meshing + ready + cancelled
}

class GenResult(val key: Long, val chunk: Chunk)
