package strata.renderer

/**
 * Chunk mesh data - generated by mesher, consumed by Vulkan renderer
 */
data class ChunkMeshData(
    val position: Triple<Int, Int, Int>,
    val vertices: FloatArray,
    val indices: IntArray
)

/**
 * Mesh builder for chunks - greedy meshing or simple culling mesher
 */
class ChunkMesher {

    fun meshChunk(
        blocks: ShortArray,
        chunkX: Int,
        chunkY: Int,
        chunkZ: Int,
        getBlock: (Int, Int, Int) -> Short
    ): ChunkMeshData {
        val vertices = mutableListOf<Float>()
        val indices = mutableListOf<Int>()
        var vertexCount = 0

        val size = 16
        val height = 16

        for (y in 0 until height) {
            for (z in 0 until size) {
                for (x in 0 until size) {
                    val block = blocks[(y * size + z) * size + x]
                    if (block.toInt() == 0) continue // Skip air

                    val wx = chunkX * 16 + x
                    val wy = chunkY * 16 + y
                    val wz = chunkZ * 16 + z

                    // Check each face and add if neighbor is air
                    // Front face (z+)
                    if (getBlock(wx, wy, wz + 1).toInt() == 0) {
                        addFace(vertices, indices, wx, wy, wz, 0, vertexCount)
                        vertexCount += 4
                    }
                    // Back face (z-)
                    if (getBlock(wx, wy, wz - 1).toInt() == 0) {
                        addFace(vertices, indices, wx, wy, wz, 1, vertexCount)
                        vertexCount += 4
                    }
                    // Left face (x-)
                    if (getBlock(wx - 1, wy, wz).toInt() == 0) {
                        addFace(vertices, indices, wx, wy, wz, 2, vertexCount)
                        vertexCount += 4
                    }
                    // Right face (x+)
                    if (getBlock(wx + 1, wy, wz).toInt() == 0) {
                        addFace(vertices, indices, wx, wy, wz, 3, vertexCount)
                        vertexCount += 4
                    }
                    // Top face (y+)
                    if (getBlock(wx, wy + 1, wz).toInt() == 0) {
                        addFace(vertices, indices, wx, wy, wz, 4, vertexCount)
                        vertexCount += 4
                    }
                    // Bottom face (y-)
                    if (getBlock(wx, wy - 1, wz).toInt() == 0) {
                        addFace(vertices, indices, wx, wy, wz, 5, vertexCount)
                        vertexCount += 4
                    }
                }
            }
        }

        return ChunkMeshData(
            position = Triple(chunkX, chunkY, chunkZ),
            vertices = vertices.toFloatArray(),
            indices = indices.toIntArray()
        )
    }

    private fun addFace(
        vertices: MutableList<Float>,
        indices: MutableList<Int>,
        x: Int, y: Int, z: Int,
        face: Int,
        vertexOffset: Int
    ) {
        // Face definitions: 4 vertices per face, 2 triangles (6 indices)
        val faceVertices = when (face) {
            0 -> floatArrayOf( // Front (z+1)
                x - 0.5f, y - 0.5f, z + 0.5f,
                x + 0.5f, y - 0.5f, z + 0.5f,
                x + 0.5f, y + 0.5f, z + 0.5f,
                x - 0.5f, y + 0.5f, z + 0.5f
            )
            1 -> floatArrayOf( // Back (z-1)
                x + 0.5f, y - 0.5f, z - 0.5f,
                x - 0.5f, y - 0.5f, z - 0.5f,
                x - 0.5f, y + 0.5f, z - 0.5f,
                x + 0.5f, y + 0.5f, z - 0.5f
            )
            2 -> floatArrayOf( // Left (x-1)
                x - 0.5f, y - 0.5f, z - 0.5f,
                x - 0.5f, y - 0.5f, z + 0.5f,
                x - 0.5f, y + 0.5f, z + 0.5f,
                x - 0.5f, y + 0.5f, z - 0.5f
            )
            3 -> floatArrayOf( // Right (x+1)
                x + 0.5f, y - 0.5f, z + 0.5f,
                x + 0.5f, y - 0.5f, z - 0.5f,
                x + 0.5f, y + 0.5f, z - 0.5f,
                x + 0.5f, y + 0.5f, z + 0.5f
            )
            4 -> floatArrayOf( // Top (y+1)
                x - 0.5f, y + 0.5f, z + 0.5f,
                x + 0.5f, y + 0.5f, z + 0.5f,
                x + 0.5f, y + 0.5f, z - 0.5f,
                x - 0.5f, y + 0.5f, z - 0.5f
            )
            5 -> floatArrayOf( // Bottom (y-1)
                x - 0.5f, y - 0.5f, z - 0.5f,
                x + 0.5f, y - 0.5f, z - 0.5f,
                x + 0.5f, y - 0.5f, z + 0.5f,
                x - 0.5f, y - 0.5f, z + 0.5f
            )
            else -> FloatArray(0)
        }

        vertices.addAll(faceVertices.toList())

        // Two triangles per face
        indices.add(vertexOffset)
        indices.add(vertexOffset + 1)
        indices.add(vertexOffset + 2)
        indices.add(vertexOffset)
        indices.add(vertexOffset + 2)
        indices.add(vertexOffset + 3)
    }
}
