package strata.cimgui

import kotlinx.cinterop.COpaquePointer
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.memScoped
import platform.posix.printf

/**
 * Desktop (Kotlin/Native) implementation of StrataImGui.
 * Bridges to the C++ strata_imgui.cpp stubs.
 */
@OptIn(ExperimentalForeignApi::class)
actual object StrataImGui {

    private var initialized = false

    actual fun init(
        instance: COpaquePointer,
        physicalDevice: COpaquePointer,
        device: COpaquePointer,
        queueFamily: Int,
        queue: COpaquePointer,
        surface: COpaquePointer,
        window: COpaquePointer,
        minImageCount: ULong
    ): Boolean {
        if (initialized) return true

        val result = memScoped {
            strata_imgui_init(
                instance,
                physicalDevice,
                device,
                queueFamily.toUInt(),
                queue,
                surface,
                window,
                minImageCount.toUInt()
            )
        }

        initialized = result == 0
        printf("[IMGUI] Init %s\n", if (initialized) "success" else "failed (code $result)")
        return initialized
    }

    actual fun shutdown() {
        if (!initialized) return
        memScoped { strata_imgui_shutdown() }
        initialized = false
        printf("[IMGUI] Shutdown complete\n")
    }

    actual fun newFrame() {
        if (!initialized) return
        memScoped { strata_imgui_new_frame() }
    }

    actual fun processEvent(event: COpaquePointer): Boolean {
        if (!initialized) return false
        return memScoped {
            strata_imgui_process_event(event)
        } != 0
    }

    actual fun wantCaptureMouse(): Boolean {
        if (!initialized) return false
        return memScoped { strata_imgui_want_capture_mouse() } != 0
    }

    actual fun wantCaptureKeyboard(): Boolean {
        if (!initialized) return false
        return memScoped { strata_imgui_want_capture_keyboard() } != 0
    }

    actual fun nativeModsScreen(): Int {
        if (!initialized) return 0
        return memScoped { strata_imgui_native_mods_screen() }
    }

    actual fun isInitialized(): Boolean = initialized

    actual fun prepareRender() {
        if (!initialized) return
        memScoped { strata_imgui_prepare_render() }
    }

    actual fun hasDrawData(): Boolean {
        if (!initialized) return false
        return memScoped { strata_imgui_has_draw_data() } != 0
    }
}

// Foreign function declarations (generated by cinterop from strata_imgui.h)
@OptIn(ExperimentalForeignApi::class)
private external fun strata_imgui_init(
    instance: COpaquePointer,
    physicalDevice: COpaquePointer,
    device: COpaquePointer,
    queueFamily: UInt,
    queue: COpaquePointer,
    surface: COpaquePointer,
    window: COpaquePointer,
    minImageCount: UInt
): Int

@OptIn(ExperimentalForeignApi::class)
private external fun strata_imgui_shutdown()
private external fun strata_imgui_new_frame()
private external fun strata_imgui_process_event(eventPtr: COpaquePointer): Int
private external fun strata_imgui_want_capture_mouse(): Int
private external fun strata_imgui_want_capture_keyboard(): Int
private external fun strata_imgui_native_mods_screen(): Int
private external fun strata_imgui_prepare_render()
private external fun strata_imgui_has_draw_data(): Int
