package strata.security.copyright

object NsfwWordDB {

    // Sexual anatomy (deny on any match)
    val anatomyPatterns = listOf(
        Regex("""\bpenis\b""", RegexOption.IGNORE_CASE),
        Regex("""\bvagina\b""", RegexOption.IGNORE_CASE),
        Regex("""\bballs\b""", RegexOption.IGNORE_CASE),
        Regex("""\btesticle\b""", RegexOption.IGNORE_CASE),
        Regex("""\bclit\b""", RegexOption.IGNORE_CASE),
        Regex("""\bclitoris\b""", RegexOption.IGNORE_CASE),
        Regex("""\blabia\b""", RegexOption.IGNORE_CASE),
        Regex("""\bscrotum\b""", RegexOption.IGNORE_CASE),
        Regex("""\basshole\b""", RegexOption.IGNORE_CASE),
        Regex("""\banus\b""", RegexOption.IGNORE_CASE),
        Regex("""\bnipple\b""", RegexOption.IGNORE_CASE),
        Regex("""\bareola\b""", RegexOption.IGNORE_CASE),
        Regex("""\bpubic\b""", RegexOption.IGNORE_CASE),
        Regex("""\bgenital\b""", RegexOption.IGNORE_CASE),
        Regex("""\bphallus\b""", RegexOption.IGNORE_CASE),
        Regex("""\burethra\b""", RegexOption.IGNORE_CASE),
        Regex("""\bwomb\b""", RegexOption.IGNORE_CASE),
        Regex("""\bbreast\b""", RegexOption.IGNORE_CASE),
        Regex("""\bboob\b""", RegexOption.IGNORE_CASE),
        Regex("""\bboobs\b""", RegexOption.IGNORE_CASE),
        Regex("""\btit\b""", RegexOption.IGNORE_CASE),
        Regex("""\btits\b""", RegexOption.IGNORE_CASE),
        Regex("""\btitty\b""", RegexOption.IGNORE_CASE),
        Regex("""\bdick\b""", RegexOption.IGNORE_CASE),
        Regex("""\bcock\b""", RegexOption.IGNORE_CASE),
        Regex("""\bdildo\b""", RegexOption.IGNORE_CASE),
        Regex("""\bdong\b""", RegexOption.IGNORE_CASE),
        Regex("""\bphallus\b""", RegexOption.IGNORE_CASE),
        Regex("""\bpecker\b""", RegexOption.IGNORE_CASE),
        Regex("""\bwang\b""", RegexOption.IGNORE_CASE),
        Regex("""\bschlong\b""", RegexOption.IGNORE_CASE),
        Regex("""\bussy\b""", RegexOption.IGNORE_CASE),
        Regex("""\bpussy\b""", RegexOption.IGNORE_CASE),
        Regex("""\bcunt\b""", RegexOption.IGNORE_CASE),
        Regex("""\bslit\b""", RegexOption.IGNORE_CASE),
        Regex("""\bsnatch\b""", RegexOption.IGNORE_CASE),
        Regex("""\bpubes\b""", RegexOption.IGNORE_CASE),
        Regex("""\bthong\b""", RegexOption.IGNORE_CASE),
    )

    // Sexual acts (deny on any match)
    val actsPatterns = listOf(
        Regex("""\bfuck\b""", RegexOption.IGNORE_CASE),
        Regex("""\bfucking\b""", RegexOption.IGNORE_CASE),
        Regex("""\bfucked\b""", RegexOption.IGNORE_CASE),
        Regex("""\bfucker\b""", RegexOption.IGNORE_CASE),
        Regex("""\bfucks\b""", RegexOption.IGNORE_CASE),
        Regex("""\bsuck\b""", RegexOption.IGNORE_CASE),
        Regex("""\bsucks?\s+(cock|dick|penis|balls?|tit|tits|pussy|cunt)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bjerk\s+off\b""", RegexOption.IGNORE_CASE),
        Regex("""\bjerkoff\b""", RegexOption.IGNORE_CASE),
        Regex("""\bmasturbat\b""", RegexOption.IGNORE_CASE),
        Regex("""\bstroke\s+(cock|dick|off)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bhandjob\b""", RegexOption.IGNORE_CASE),
        Regex("""\bblowjob\b""", RegexOption.IGNORE_CASE),
        Regex("""\bdeepthroat\b""", RegexOption.IGNORE_CASE),
        Regex("""\bgangbang\b""", RegexOption.IGNORE_CASE),
        Regex("""\bthreesome\b""", RegexOption.IGNORE_CASE),
        Regex("""\borg(y|ies)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bincest\b""", RegexOption.IGNORE_CASE),
        Regex("""\bbestiality\b""", RegexOption.IGNORE_CASE),
        Regex("""\bzoophil\b""", RegexOption.IGNORE_CASE),
        Regex("""\bsexually?\b""", RegexOption.IGNORE_CASE),
        Regex("""\bsexual\b""", RegexOption.IGNORE_CASE),
        Regex("""\bcum\b""", RegexOption.IGNORE_CASE),
        Regex("""\bcumming\b""", RegexOption.IGNORE_CASE),
        Regex("""\bcreampie\b""", RegexOption.IGNORE_CASE),
        Regex("""\bsemen\b""", RegexOption.IGNORE_CASE),
        Regex("""\bejacul\b""", RegexOption.IGNORE_CASE),
        Regex("""\bspunk\b""", RegexOption.IGNORE_CASE),
        Regex("""\bintercourse\b""", RegexOption.IGNORE_CASE),
        Regex("""\bcopulat\b""", RegexOption.IGNORE_CASE),
        Regex("""\bfornicat\b""", RegexOption.IGNORE_CASE),
        Regex("""\bpenetrat\b""", RegexOption.IGNORE_CASE),
        Regex("""\bhentai\b""", RegexOption.IGNORE_CASE),
        Regex("""\bdoujin\b""", RegexOption.IGNORE_CASE),
        Regex("""\bahegao\b""", RegexOption.IGNORE_CASE),
        Regex("""\brule34\b""", RegexOption.IGNORE_CASE),
        Regex("""\bsex\b""", RegexOption.IGNORE_CASE),
    )

    // Adult content descriptors (flags for review)
    val adultPatterns = listOf(
        Regex("""\bporn\b""", RegexOption.IGNORE_CASE),
        Regex("""\bporno\b""", RegexOption.IGNORE_CASE),
        Regex("""\bnude\b""", RegexOption.IGNORE_CASE),
        Regex("""\bnudity\b""", RegexOption.IGNORE_CASE),
        Regex("""\bnaked\b""", RegexOption.IGNORE_CASE),
        Regex("""\bxxx\b""", RegexOption.IGNORE_CASE),
        Regex("""\bbdsm\b""", RegexOption.IGNORE_CASE),
        Regex("""\bstripper\b""", RegexOption.IGNORE_CASE),
        Regex("""\bstripclub\b""", RegexOption.IGNORE_CASE),
        Regex("""\bstrip\s+club\b""", RegexOption.IGNORE_CASE),
        Regex("""\berotic\b""", RegexOption.IGNORE_CASE),
        Regex("""\blewd\b""", RegexOption.IGNORE_CASE),
        Regex("""\bfetish\b""", RegexOption.IGNORE_CASE),
        Regex("""\bwaifu\b""", RegexOption.IGNORE_CASE),
        Regex("""\boppai\b""", RegexOption.IGNORE_CASE),
        Regex("""\bnsfw\b""", RegexOption.IGNORE_CASE),
        Regex("""\badult\s*(content|mod|game|sim|video|movie|film)\b""", RegexOption.IGNORE_CASE),
        Regex("""\b18\+\b""", RegexOption.IGNORE_CASE),
        Regex("""\badultmod\b""", RegexOption.IGNORE_CASE),
        Regex("""\bsexytoy\b""", RegexOption.IGNORE_CASE),
        Regex("""\bsex\s+toy\b""", RegexOption.IGNORE_CASE),
        Regex("""\bvibrator\b""", RegexOption.IGNORE_CASE),
        Regex("""\blingerie\b""", RegexOption.IGNORE_CASE),
        Regex("""\bondage\b""", RegexOption.IGNORE_CASE),
        Regex("""\bdominatrix\b""", RegexOption.IGNORE_CASE),
        Regex("""\blatex\b""", RegexOption.IGNORE_CASE),
        Regex("""\bonlyfans\b""", RegexOption.IGNORE_CASE),
        Regex("""\bfansly\b""", RegexOption.IGNORE_CASE),
        Regex("""\bmilf\b""", RegexOption.IGNORE_CASE),
        Regex("""\bcams?\s*(girl|model|show|site)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bwebcam\s*(girl|model|show)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bexplicit\b""", RegexOption.IGNORE_CASE),
        Regex("""\buncesored\b""", RegexOption.IGNORE_CASE),
        Regex("""\bnaughty\b""", RegexOption.IGNORE_CASE),
    )

    // CSAM patterns (CRITICAL — delete and report)
    val csamPatterns = listOf(
        Regex("""\bchild\s*(sex|porn|nude|abuse|exploit)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bminor\s*(nude|porn|sex)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bunderage\s*(sex|nude|porn)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bloli\b""", RegexOption.IGNORE_CASE),
        Regex("""\bshota\b""", RegexOption.IGNORE_CASE),
        Regex("""\bshotacon\b""", RegexOption.IGNORE_CASE),
        Regex("""\blolicon\b""", RegexOption.IGNORE_CASE),
        Regex("""\byoung\s*(nude|porn|sex)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bteen\s*(nude|porn|sex|pics|photos)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bkid\s*(nude|porn|sex|pics)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bbaby\s*(nude|porn|sex)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bgrooming\b""", RegexOption.IGNORE_CASE),
        Regex("""\bcsam\b""", RegexOption.IGNORE_CASE),
        Regex("""\bcsa\s+material\b""", RegexOption.IGNORE_CASE),
        Regex("""\bchild\s+abuse\b""", RegexOption.IGNORE_CASE),
    )

    // Grooming / off-platform contact / social engineering
    val groomingPatterns = listOf(
        Regex("""\badd\s+me\s+on\s+(discord|snap|snapchat|telegram|kik|whatsapp|signal|instagram)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bdm\s+me\b""", RegexOption.IGNORE_CASE),
        Regex("""\bprivate\s+(chat|message|dm|msg)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bdon.?t\s+tell\s+(anyone|mom|dad|parent|teacher)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bkeep\s+this\s+(secret|private|between\s+us)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bhide\s+this\b""", RegexOption.IGNORE_CASE),
        Regex("""\bdelete\s+these\s+messages\b""", RegexOption.IGNORE_CASE),
        Regex("""\bprove\s+(you|your)\s+(are|not)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bhow\s+old\s+are\s+you\b""", RegexOption.IGNORE_CASE),
        Regex("""\bare\s+you\s+(home\s+)?alone\b""", RegexOption.IGNORE_CASE),
        Regex("""\bsend\s+(me\s+)?(pics?|photos?|pictures?)\b""", RegexOption.IGNORE_CASE),
        Regex("""\bcam\s+to\s+cam\b""", RegexOption.IGNORE_CASE),
        Regex("""\bvideo\s+call\s+me\b""", RegexOption.IGNORE_CASE),
        Regex("""\byou\s+(look|are|seem)\s+(cute|pretty|hot|sexy)\b""", RegexOption.IGNORE_CASE),
    )

    val allPatterns: List<Regex> by lazy {
        anatomyPatterns + actsPatterns + adultPatterns
    }
}
